server:
  port: 8080

spring:
  profiles: default
  http:
    #한글관련 UTF-8 설정.
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 연결설정 유니코드사용 :
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: schiva
    password: 1111
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2


# 출력되는 로그에 색상 출력
  output:
    ansi:
      enabled: always

#logging:
#  file: ./log
#  level:
#    root: INFO
#    com.example.demo: INFO


mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package:


#  configuration:
#    lazyLoadingEnabled=true
#    aggressiveLazyLoading=false
#    mapUnderscoreToCamelCase=true

# mybatis 매핑 type을 짧게 쓰기 위한 설정
#  mybatis.type-aliases-package=net.chndol.study.mybatissample.model

  # mapper 이하를 로깅 위치로 설정.
#  logging.level.net.chndol.study.mybatissample.mapper=TRACE




